### ISSUE TITLE
minecraft wont start

### ISSUE THREAD

**Issue by toti787** [dslake/WorldDownloader#38]
when i click start it loads and then crashes here is the code:

& Libraries'... (try 0)
[07:05:54 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar for job 'Version & Libraries'... (try 0)
[07:05:54 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1-nightly-20131017/lwjgl-platform-2.9.1-nightly-20131017-natives-osx.jar for job 'Version & Libraries'... (try 0)
[07:05:54 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar for job 'Version & Libraries'... (try 0)
[07:05:54 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar for job 'Version & Libraries'... (try 0)
[07:05:54 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar for job 'Version & Libraries'... (try 0)
[07:05:54 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar for job 'Version & Libraries'... (try 0)
[07:05:54 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar for job 'Version & Libraries'... (try 0)
[07:05:54 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar for job 'Version & Libraries'... (try 0)
[07:05:54 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar for job 'Version & Libraries'... (try 0)
[07:05:54 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar for job 'Version & Libraries'... (try 0)
[07:05:54 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar for job 'Version & Libraries'... (try 0)
[07:05:54 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1-nightly-20131017/lwjgl_util-2.9.1-nightly-20131017.jar for job 'Version & Libraries'... (try 0)
[07:05:54 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar for job 'Version & Libraries'... (try 0)
[07:05:54 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar for job 'Version & Libraries'... (try 0)
[07:05:54 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1-nightly-20131017/lwjgl-2.9.1-nightly-20131017.jar for job 'Version & Libraries'... (try 0)
[07:05:56 INFO](Job): Download job 'Resources' skipped as there are no files to download

[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1-nightly-20131017/lwjgl-2.9.1-nightly-20131017.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar for job 'Version & Libraries'... (try 0)
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar for job 'Version & Libraries'... (try 0)
[07:05:56 INFO](Job): Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar for job 'Version & Libraries'... (try 0)
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1-nightly-20131017/lwjgl_util-2.9.1-nightly-20131017.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/com/mojang/authlib/1.3/authlib-1.3.jar for job 'Version & Libraries'... (try 0)
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/com/google/guava/guava/15.0/guava-15.0.jar for job 'Version & Libraries'... (try 0)
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/com/mojang/authlib/1.3/authlib-1.3.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar for job 'Version & Libraries'... (try 0)
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Attempting to download /Users/toti2/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar for job 'Version & Libraries'... (try 0)
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Attempting to download /Users/toti2/Library/Application Support/minecraft/versions/downloder/downloder.jar for job 'Version & Libraries'... (try 0)
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1-nightly-20131017/lwjgl-platform-2.9.1-nightly-20131017-natives-osx.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 INFO](Job): Finished downloading /Users/toti2/Library/Application Support/minecraft/libraries/com/google/guava/guava/15.0/guava-15.0.jar for job 'Version & Libraries': Local file matches local checksum, using that
[07:05:56 WARN]: Couldn't download https://s3.amazonaws.com/Minecraft.Download/versions/downloder/downloder.jar for job 'Version & Libraries'
java.lang.RuntimeException: Server responded with 403
    at net.minecraft.launcher.updater.download.EtagDownloadable.download(EtagDownloadable.java:43) ~[launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:108) [launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:12) [launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:89) [launcher.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [?:1.6.0_65]
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [?:1.6.0_65]
    at java.util.concurrent.FutureTask.run(FutureTask.java:138) [?:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [?:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [?:1.6.0_65]
    at java.lang.Thread.run(Thread.java:695) [?:1.6.0_65](Job): Attempting to download /Users/toti2/Library/Application Support/minecraft/versions/downloder/downloder.jar for job 'Version & Libraries'... (try 1)
[07:05:57 WARN]: Couldn't download https://s3.amazonaws.com/Minecraft.Download/versions/downloder/downloder.jar for job 'Version & Libraries'
java.lang.RuntimeException: Server responded with 403
    at net.minecraft.launcher.updater.download.EtagDownloadable.download(EtagDownloadable.java:43) ~[launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:108) [launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:12) [launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:89) [launcher.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [?:1.6.0_65]
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [?:1.6.0_65]
    at java.util.concurrent.FutureTask.run(FutureTask.java:138) [?:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [?:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [?:1.6.0_65]
    at java.lang.Thread.run(Thread.java:695) [?:1.6.0_65]
[07:05:57 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/versions/downloder/downloder.jar for job 'Version & Libraries'... (try 2)
[07:05:58 WARN]: Couldn't download https://s3.amazonaws.com/Minecraft.Download/versions/downloder/downloder.jar for job 'Version & Libraries'
java.lang.RuntimeException: Server responded with 403
    at net.minecraft.launcher.updater.download.EtagDownloadable.download(EtagDownloadable.java:43) ~[launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:108) [launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:12) [launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:89) [launcher.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [?:1.6.0_65]
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [?:1.6.0_65]
    at java.util.concurrent.FutureTask.run(FutureTask.java:138) [?:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [?:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [?:1.6.0_65]
    at java.lang.Thread.run(Thread.java:695) [?:1.6.0_65]
[07:05:58 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/versions/downloder/downloder.jar for job 'Version & Libraries'... (try 3)
[07:05:58 WARN]: Couldn't download https://s3.amazonaws.com/Minecraft.Download/versions/downloder/downloder.jar for job 'Version & Libraries'
java.lang.RuntimeException: Server responded with 403
    at net.minecraft.launcher.updater.download.EtagDownloadable.download(EtagDownloadable.java:43) ~[launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:108) [launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:12) [launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:89) [launcher.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [?:1.6.0_65]
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [?:1.6.0_65]
    at java.util.concurrent.FutureTask.run(FutureTask.java:138) [?:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [?:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [?:1.6.0_65]
    at java.lang.Thread.run(Thread.java:695) [?:1.6.0_65]
[07:05:58 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/versions/downloder/downloder.jar for job 'Version & Libraries'... (try 4)
[07:05:59 WARN]: Couldn't download https://s3.amazonaws.com/Minecraft.Download/versions/downloder/downloder.jar for job 'Version & Libraries'
java.lang.RuntimeException: Server responded with 403
    at net.minecraft.launcher.updater.download.EtagDownloadable.download(EtagDownloadable.java:43) ~[launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:108) [launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:12) [launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:89) [launcher.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [?:1.6.0_65]
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [?:1.6.0_65]
    at java.util.concurrent.FutureTask.run(FutureTask.java:138) [?:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [?:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [?:1.6.0_65]
    at java.lang.Thread.run(Thread.java:695) [?:1.6.0_65]
[07:05:59 INFO]: Attempting to download /Users/toti2/Library/Application Support/minecraft/versions/downloder/downloder.jar for job 'Version & Libraries'... (try 5)
[07:06:00 WARN]: Couldn't download https://s3.amazonaws.com/Minecraft.Download/versions/downloder/downloder.jar for job 'Version & Libraries'
java.lang.RuntimeException: Server responded with 403
    at net.minecraft.launcher.updater.download.EtagDownloadable.download(EtagDownloadable.java:43) ~[launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:108) [launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:12) [launcher.jar:?]
    at net.minecraft.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:89) [launcher.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [?:1.6.0_65]
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [?:1.6.0_65]
    at java.util.concurrent.FutureTask.run(FutureTask.java:138) [?:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [?:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [?:1.6.0_65]
    at java.lang.Thread.run(Thread.java:695) [?:1.6.0_65](Job): Gave up trying to download https://s3.amazonaws.com/Minecraft.Download/versions/downloder/downloder.jar for job 'Version & Libraries'

**Comment by dslake** [comment]
You didn't install it correctly. This line indicates your config file (.json) and enclosing folder are messed up. I'd guess you didn't edit the json properly. Try MagicLauncher. It makes it very easy.

"Attempting to download /Users/toti2/Library/Application Support/minecraft/versions/downloder/downloder.jar"
