### ISSUE TITLE
[Beta v3] Crashes after death and respawn

### ISSUE THREAD

**Issue by netvnum** [dslake/WorldDownloader#4]
I also reported this issue in the Beta v2, and have been able to re-produce the same problem in Beta v3. After dying, and clicking on Respawn, Minecraft crashes with the following error:

java.lang.RuntimeException: World Downloader: Couldn't stop download! Check your worlds!
    at WDL.onWorldLoad(WDL.java:157)
    at atd.a(WorldClient.java:150)
    at asv.a(NetClientHandler.java:562)
    at cn.a(SourceFile:97)
    at bb.b(SourceFile:333)
    at asv.d(NetClientHandler.java:89)
    at atd.b(WorldClient.java:63)
    at net.minecraft.client.Minecraft.l(SourceFile:1261)
    at net.minecraft.client.Minecraft.J(SourceFile:583)
    at net.minecraft.client.Minecraft.run(SourceFile:535)
    at java.lang.Thread.run(Unknown Source)

I have been able to re-produce this crash with auto download turned ON, and only in menu turned ON.

**Comment by dslake** [comment]
Thanks for opening this up again. There may be a timing issue at play here because it seemed that the issue was fixed by Nairol's commit. I'll continue to look through this issue.

**Comment by nairol** [comment]
I didn't fix anything regarding this issue.
I fixed the `mc.thePlayer == null` problem. (Issue #1)

The 3 currently open issues look very alike:
Same line in the same file after the same action (unloading world, then loading world).

**Comment by dslake** [comment]
I posted BETA 6 in the forums which should fix this crash.
