### ISSUE TITLE
Game Fails to Launch - 1.7.2

### ISSUE THREAD

**Issue by flarsh** [dslake/WorldDownloader#43]
Hey guys! I think this mod is a fantastic idea, as I have had many builds on servers which I had no chance of retrieving. I've tried multiple times to get this mod to work, both with MagicLauncher and without, to no avail. I decided to try again, and post something asking for help.

Thanks a bunch!

(Running OSX 10.8.5)

Here's my crash report:

[19:35:43 INFO]: Minecraft Launcher 1.3.10 (through bootstrap 5) started on osx...
[19:35:43 INFO]: Current time is Feb 13, 2014 7:35:43 PM
[19:35:43 INFO]: Refreshing local version list...
[19:35:43 INFO]: System.getProperty('os.name') == 'Mac OS X'
[19:35:43 INFO]: System.getProperty('os.version') == '10.8.5'
[19:35:43 INFO]: System.getProperty('os.arch') == 'x86_64'
[19:35:43 INFO]: System.getProperty('java.version') == '1.6.0_51'
[19:35:43 INFO]: System.getProperty('java.vendor') == 'Apple Inc.'
[19:35:43 INFO]: System.getProperty('sun.arch.data.model') == '64'
[19:35:43 INFO]: Refreshing remote version list...
[19:35:44 INFO]: Refresh complete.
[19:35:44 INFO]: Loaded 7 profile(s); selected 'World Downloader'
[19:35:44 INFO]: Refreshing auth...
[19:35:44 INFO]: Logging in with access token
[19:35:53 INFO]: Getting syncinfo for selected version
[19:35:53 INFO]: Queueing library & version downloads
[19:35:53 INFO]: Download job 'Version & Libraries' started (16 threads, 24 files)
[19:35:53 INFO]: Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar for job 'Version & Libraries'... (try 0)
[19:35:53 INFO]: Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/com/mojang/authlib/1.3/authlib-1.3.jar for job 'Version & Libraries'... (try 0)
[19:35:53 INFO]: Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar for job 'Version & Libraries'... (try 0)
[19:35:53 INFO]: Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar for job 'Version & Libraries'... (try 0)
[19:35:53 INFO]: Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1-nightly-20131017/lwjgl_util-2.9.1-nightly-20131017.jar for job 'Version & Libraries'... (try 0)
[19:35:53 INFO]: Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar for job 'Version & Libraries'... (try 0)
[19:35:53 INFO]: Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar for job 'Version & Libraries'... (try 0)
[19:35:53 INFO]: Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/com/google/guava/guava/15.0/guava-15.0.jar for job 'Version & Libraries'... (try 0)
[19:35:53 INFO]: Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar for job 'Version & Libraries'... (try 0)
[19:35:53 INFO]: Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar for job 'Version & Libraries'... (try 0)
[19:35:53 INFO]: Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar for job 'Version & Libraries'... (try 0)
[19:35:53 INFO]: Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar for job 'Version & Libraries'... (try 0)
[19:35:53 INFO]: Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar for job 'Version & Libraries'... (try 0)
[19:35:53 INFO]: Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1-nightly-20131017/lwjgl-2.9.1-nightly-20131017.jar for job 'Version & Libraries'... (try 0)
[19:35:53 INFO]: Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar for job 'Version & Libraries'... (try 0)
[19:35:53 INFO]: Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar for job 'Version & Libraries'... (try 0)
[19:35:55 INFO](Job): Download job 'Resources' skipped as there are no files to download

[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1-nightly-20131017/lwjgl-2.9.1-nightly-20131017.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar for job 'Version & Libraries'... (try 0)
[19:35:55 INFO](Job): Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar for job 'Version & Libraries'... (try 0)
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar for job 'Version & Libraries'... (try 0)
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar for job 'Version & Libraries'... (try 0)
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar for job 'Version & Libraries'... (try 0)
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1-nightly-20131017/lwjgl-platform-2.9.1-nightly-20131017-natives-osx.jar for job 'Version & Libraries'... (try 0)
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Attempting to download /Users/<me>/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar for job 'Version & Libraries'... (try 0)
[19:35:55 INFO](Job): Attempting to download /Users/<me>/Library/Application Support/minecraft/versions/downloader/downloader.jar for job 'Version & Libraries'... (try 0)
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1-nightly-20131017/lwjgl-platform-2.9.1-nightly-20131017-natives-osx.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/com/google/guava/guava/15.0/guava-15.0.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1-nightly-20131017/lwjgl_util-2.9.1-nightly-20131017.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/com/mojang/authlib/1.3/authlib-1.3.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar for job 'Version & Libraries': Local file matches local checksum, using that
[19:35:55 INFO](Job): Finished downloading /Users/<me>/Library/Application Support/minecraft/versions/downloader/downloader.jar for job 'Version & Libraries': Couldn't connect to server (responded with 403) but have local file, assuming it's good

[19:35:55 INFO](Job): Launching game
[19:35:55 INFO](Job): Looking for old natives & assets to clean up...
[19:35:55 INFO](Job): Unpacking natives to /Users/<me>/Library/Application Support/minecraft/versions/downloader/downloader-natives-1392338155288027000
[19:35:55 INFO](Job): Reconstructing virtual assets folder at /Users/<me>/Library/Application Support/minecraft/assets/virtual/legacy
[19:35:55 INFO](Job): Launching in /Users/<me>/Library/Application Support/minecraft
[19:35:55 INFO](Job): Half command: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java -Xdock:icon=/Users/<me>/Library/Application Support/minecraft/assets/objects/99/991b421dfd401f115241601b2b373140a8d78572 -Xdock:name=Minecraft -Xmx1G -Djava.library.path=/Users/<me>/Library/Application Support/minecraft/versions/downloader/downloader-natives-1392338155288027000 -cp /Users/<me>/Library/Application Support/minecraft/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar:/Users/<me>/Library/Application Support/minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar:/Users/<me>/Library/Application Support/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/Users/<me>/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar:/Users/<me>/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/Users/<me>/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/Users/<me>/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/Users/<me>/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:/Users/<me>/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/Users/<me>/Library/Application Support/minecraft/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar:/Users/<me>/Library/Application Support/minecraft/libraries/com/google/guava/guava/15.0/guava-15.0.jar:/Users/<me>/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar:/Users/<me>/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/<me>/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/Users/<me>/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/Users/<me>/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar:/Users/<me>/Library/Application Support/minecraft/libraries/com/mojang/authlib/1.3/authlib-1.3.jar:/Users/<me>/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar:/Users/<me>/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar:/Users/<me>/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1-nightly-20131017/lwjgl-2.9.1-nightly-20131017.jar:/Users/<me>/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1-nightly-20131017/lwjgl_util-2.9.1-nightly-20131017.jar:/Users/<me>/Library/Application Support/minecraft/versions/downloader/downloader.jar net.minecraft.client.main.Main
[19:35:55 INFO](Job): Client> Exception in thread "main" java.lang.NoClassDefFoundError: net/minecraft/client/main/Main
[19:35:55 INFO](Job): Client> Caused by: java.lang.ClassNotFoundException: net.minecraft.client.main.Main
[19:35:55 INFO](Job): Client>    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
[19:35:55 INFO](Job): Client>    at java.security.AccessController.doPrivileged(Native Method)
[19:35:55 INFO](Job): Client>    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[19:35:55 INFO](Job): Client>    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[19:35:55 INFO](Job): Client>    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
[19:35:55 INFO](Job): Client>    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[19:35:55 ERROR]: Game ended with bad state (exit code 1)
[19:35:55 INFO](Job): Deleting /Users/<me>/Library/Application Support/minecraft/versions/downloader/downloader-natives-1392338155288027000
[19:35:55 INFO](Job): Ignoring visibility rule and showing launcher due to a game crash

**Comment by nairol** [comment]
Doesn't look like a World Downloader bug. There is nothing WDL specific in this error message.

This looks like your problem: https://bugs.mojang.com/browse/MCL-412
