### ISSUE TITLE
World Downloader Mod crashing upon Saving World

### ISSUE THREAD

**Issue by wismicuwu** [dslake/WorldDownloader#70]
World Downloader Mod crashes upon Saving World, regardless of how many chunks, settings, etc are changed before beginning the process. I don't often times use this mod nor know my way around a crash report that well anymore. Could use help to get this working, thanks!

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 3/20/20 12:27 PM
Description: mouseClicked event handler

java.lang.NullPointerException: mouseClicked event handler
	at wdl.WDL.saveProps(WDL.java:1087)
	at wdl.WDL.saveProps(WDL.java:1077)
	at wdl.WDL$2.onSelect(WDL.java:359)
	at wdl.gui.GuiWDLMultiworld$3.performAction(GuiWDLMultiworld.java:80)
	at wdl.gui.widget.ExtButton.onPress(ExtButton_1_14.java:41)
	at wdl.gui.widget.WDLButton.onPress(WDLButton.java:19)
	at czd.onClick(SourceFile:15)
	at czg.mouseClicked(SourceFile:154)
	at wdl.gui.widget.ExtButton.mouseClicked(ExtButton_1_14.java:49)
	at wdl.gui.widget.WDLButton.mouseClicked(WDLButton.java:19)
	at dad.mouseClicked(SourceFile:27)
	at wdl.gui.widget.ExtGuiScreen.mouseClicked(ExtGuiScreen_1_14.java:80)
	at cyd.b(SourceFile:86)
	at dcl.wrapScreenError(SourceFile:441)
	at cyd.a(SourceFile:86)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at cuo.k(MainWindow.java:503)
	at cuo.c(MainWindow.java:342)
	at cyc.b(SourceFile:1023)
	at cyc.e(SourceFile:976)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at wdl.WDL.saveProps(WDL.java:1087)
	at wdl.WDL.saveProps(WDL.java:1077)
	at wdl.WDL$2.onSelect(WDL.java:359)
	at wdl.gui.GuiWDLMultiworld$3.performAction(GuiWDLMultiworld.java:80)
	at wdl.gui.widget.ExtButton.onPress(ExtButton_1_14.java:41)
	at wdl.gui.widget.WDLButton.onPress(WDLButton.java:19)
	at czd.onClick(SourceFile:15)
	at czg.mouseClicked(SourceFile:154)
	at wdl.gui.widget.ExtButton.mouseClicked(ExtButton_1_14.java:49)
	at wdl.gui.widget.WDLButton.mouseClicked(WDLButton.java:19)
	at dad.mouseClicked(SourceFile:27)
	at wdl.gui.widget.ExtGuiScreen.mouseClicked(ExtGuiScreen_1_14.java:80)
	at cyd.b(SourceFile:86)

-- Affected screen --
Details:
	Screen name: wdl.gui.GuiWDLMultiworld
Stacktrace:
	at dcl.wrapScreenError(SourceFile:441)
	at cyd.a(SourceFile:86)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at cuo.k(MainWindow.java:503)
	at cuo.c(MainWindow.java:342)

-- Affected level --
Details:
	All players: 1 total; [dmp['wismicuwu'/73996, l='MpServer', x=12284.77, y=93.00, z=8586.47]]
	Chunk stats: Client Chunk Cache: 729, 441
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (12316,63,8590), Chunk: (at 12,3,14 in 769,536; contains blocks 12304,0,8576 to 12319,255,8591), Region: (24,16; contains chunks 768,512 to 799,543, blocks 12288,0,8192 to 12799,255,8703)
	Level time: 158415 game time, 130556259 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dkf.a(ClientWorld.java:574)
	at cyc.b(SourceFile:1923)
	at cyc.b(SourceFile:425)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 904147912 bytes (862 MB) / 2383937536 bytes (2273 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3456m
	Launched Version: MultiMC5
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'WorldDownloader-4.0.6.2'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x AMD A10-6790K APU with Radeon(tm) HD Graphics 
	OptiFine Version: OptiFine_1.14.4_HD_U_F5
	OptiFine Build: 20191204-141250
	Render Distance Chunks: 64
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 432.00
	OpenGlRenderer: GeForce GTX 760/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by ghost** [comment]
This mod is for old versions on Minecraft and will not work on modern.
